In [33]:
import pandas as pd
from glob import glob


stage_order = ['COAD','KIRC','LIHC','LUAD','SKCM','STAD','THCA','UCEC','LUSC','BRCA']
grade_order = ['CESC','KIRC','LGG','LIHC','PAAD','STAD','UCEC','HNSC']

In [34]:
csvs = glob('*.csv')

In [35]:
stage_res = []
grade_res = []
for csv in csvs:

    info = csv.split('_')
    model = info[0]
    task_type = info[-1].replace('.csv', '')

    dfres = pd.read_csv(csv,index_col=0)
    dfr = dfres.groupby('task').mean().sort_values('score',ascending=False)

    dfr[model] = dfr.score
    dfr.index = dfr.index.map(lambda x:x.split('_')[-2])

    if task_type == 'stage':
        order = stage_order
        dfr = dfr.loc[order]
        stage_res.append(dfr[model])
        
    else:
        order = grade_order
        dfr = dfr.loc[order]
        grade_res.append(dfr[model])

In [36]:
pd.concat(stage_res,axis=1)

           XGB       LGB  RoationForest
task
COAD  0.720343  0.706449       0.622647
KIRC  0.789194  0.793593       0.665410
LIHC  0.667300  0.649553       0.576210
LUAD  0.647783  0.642186       0.540913
SKCM  0.591943  0.646248       0.536384
STAD  0.580905  0.566451       0.501835
THCA  0.654603  0.668006       0.610401
UCEC  0.665900  0.661156       0.607296
LUSC  0.605535  0.620234       0.541173
BRCA  0.624996  0.649577       0.492303

In [37]:
pd.concat(grade_res,axis=1)

           LGB       XGB  RoationForest
task
CESC  0.606644  0.582557       0.639543
KIRC  0.594151  0.578386       0.541430
LGG   0.744572  0.736230       0.613778
LIHC  0.677298  0.650754       0.570013
PAAD  0.622926  0.622311       0.469071
STAD  0.765723  0.746808       0.617601
UCEC  0.891569  0.882266       0.716938
HNSC  0.740807  0.752417       0.620412