In [6]:
import pandas as pd
import numpy as np
#10-fold cross validation, and this was repeated for 100 times.

```Discriminant features identified from LASSO logistic regression classifiers and
random-forest classifiers for distinguishing S0 (n= 27) and SIII/IV (n= 54) cases from the healthy controls (n= 127). 
```

In [14]:
df1 = pd.read_excel('./subject.xlsx', sheet_name='616')
df2 = pd.read_excel('./subject.xlsx', sheet_name='406')

df1 = df1.set_index('Subject_ID')
df2 = df2.set_index('Subject_ID')

In [18]:
idx = list(set(df1.index) & set(df2.index))

In [21]:
df1.loc[idx].groupby('Group').size()

Group
HS               30
Healthy         127
MP               40
Stage_0          27
Stage_III_IV     54
Stage_I_II       69
dtype: int64

In [ ]:
df1 = pd.read_excel('./subject.xlsx', sheet_name='616')
df2 = pd.read_excel('./subject.xlsx', sheet_name='406')

df1 = df1.set_index('Subject_ID')
df2 = df2.set_index('Subject_ID')

commom_idx = list(set(df1.index) & set(df2.index))

df1.loc[commom_idx].to_excel('./subject_info.xlsx')


dfx = pd.read_excel('./data.xlsx', sheet_name='Species', index_col = 0)
dfx = dfx[commom_idx]
dfx = dfx.T
dfx.index = dfx.index.astype(int)
dfx.to_excel('./data_species.xlsx')


dfx = pd.read_excel('./data.xlsx', sheet_name='KO', index_col = 0)
dfx = dfx[commom_idx]
dfx = dfx.T
dfx.index = dfx.index.astype(int)
dfx.to_excel('./data_KO.xlsx')

dfx = pd.read_excel('./data.xlsx', sheet_name='Metabolite', index_col = 0)
dfx = dfx[commom_idx]
dfx = dfx.T
dfx.index = dfx.index.astype(int)
dfx.to_excel('./data_Metabolite.xlsx')

In [23]:
dfx = pd.read_excel('./8367_species.xlsx')

In [26]:
dfx.columns[-28:]

Index([10323.1, 10067.1, 10147.1, 10308.1, 10307.1, 10303.1, 10532.1, 10236.1,
       10126.1, 10103.1, 10185.1, 10603.1, 10480.1, 10745.1, 10260.1, 10333.1,
       10267.1, 10646.1, 10462.1, 10118.1, 10505.1, 10030.1, 10091.1, 10097.1,
       10099.1, 10199.1, 10717.1, 10595.1],
      dtype='object')

In [27]:
label = pd.read_excel('./subject_info.xlsx')

In [31]:
l1 = label[label.Group == 'Stage_0'].Subject_ID.tolist()

In [36]:
l2 = dfx.columns[-28:].map(lambda x:str(x).split('.')[0]).astype(int).tolist()

In [37]:
set(l1) & set(l2)

set()

In [42]:
label[label['Subject_ID'].isin(l2)]

,Subject_ID,Group,Stage,Age,Gender,BMI,Brinkman Index,Alcohol,Tumor location
14,10260,Stage_III_IV,IIIB,63,F,20.134780,0,0.0000,Right colon
19,10267,Stage_I_II,IIA,60,F,20.829995,1050,1899.0000,Right colon
40,10303,Stage_III_IV,IIIB,44,F,26.672763,0,0.0000,Right colon
43,10307,Stage_III_IV,IIIB,49,F,22.640865,0,62.1214,Left colon
44,10308,Stage_I_II,IIA,69,F,20.613131,0,44.2000,Left colon
53,10323,Stage_I_II,IIA,68,F,21.786492,300,138.0000,Rectum
60,10333,Stage_I_II,IIA,45,M,20.619254,250,618.3570,Rectum
90,10462,Stage_I_II,I,61,F,21.641274,0,0.0000,Rectum
100,10480,Stage_I_II,I,53,M,20.761246,400,1037.1400,Rectum
109,10505,Stage_I_II,IIA,65,F,17.993080,450,0.0000,Rectum
118,10532,Stage_III_IV,IIIC,60,M,23.225432,0,0.0000,Left colon
166,10646,Stage_III_IV,IIIC,67,F,20.174554,0,0.0000,Rectum
195,10717,Stage_I_II,I,69,M,22.839506,1140,0.0000,Right colon
206,10745,Stage_I_II,I,69,F,19.777699,0,0.0000,Right colon
267,10067,Stage_I_II,I,64,F,24.218750,0,0.0000,Right colon
277,10091,Stage_I_II,IIA,70,F,24.732461,0,0.0000,Left colon
280,10097,Stage_I_II,I,62,F,21.875000,0,0.0000,Left colon
281,10099,Stage_III_IV,IIIA,51,M,20.761246,405,496.5000,Rectum
283,10103,Stage_III_IV,IIIB,55,M,24.577867,30,733.0710,Rectum
291,10118,Stage_III_IV,IIIB,62,F,21.082813,250,0.0000,Left colon
295,10126,Stage_I_II,I,52,M,31.020408,640,1173.0000,Rectum
302,10147,Stage_I_II,I,51,F,18.827111,30,604.9210,Left colon
317,10185,Stage_I_II,IIA,65,M,21.718066,940,189.9000,Right colon
323,10199,Stage_I_II,I,64,M,23.051755,120,496.5000,Rectum
345,10236,Stage_I_II,I,47,M,23.566632,0,389.9000,Rectum