In [1]:
import pandas as pd
from glob import glob


stage_order = ['COAD','KIRC','LIHC','LUAD','SKCM','STAD','THCA','UCEC','LUSC','BRCA']
grade_order = ['CESC','KIRC','LGG','LIHC','PAAD','STAD','UCEC','HNSC']

In [2]:
csvs = glob('*.csv')

def get_f(x):
    res = x.sort_values().tolist()
    return '%s~%s' % (res[0], res[-1])

In [5]:
stage_res = []
grade_res = []
for csv in csvs:

    info = csv.split('_')
    model = info[1]
    task_type = info[-1].replace('.csv', '')

    dfres = pd.read_csv(csv,index_col=0)
    dfr = dfres.groupby('task').mean().sort_values('score',ascending=False)
    
    #fs = dfres.groupby('task').selected_features.apply(get_f).to_frame(name = 'fsize')
    dfr = dfr.join(fs)
    
    dfr[model] = dfr.score
    dfr.index = dfr.index.map(lambda x:x.split('_')[-2])

    if task_type == 'stage':
        order = stage_order
        dfr = dfr.loc[order]
        stage_res.append(dfr[[model]])
        
    else:
        order = grade_order
        dfr = dfr.loc[order]
        grade_res.append(dfr[[model]])

In [9]:
pd.concat(stage_res,axis=1)[['RoationForest', 'XGB', 'LGB']]

      RoationForest       XGB       LGB
task
COAD       0.626350  0.687715  0.688957
KIRC       0.668403  0.766197  0.786948
LIHC       0.589311  0.655426  0.620322
LUAD       0.542423  0.642193  0.640448
SKCM       0.649955  0.606507  0.631652
STAD       0.557601  0.528999  0.526141
THCA       0.560378  0.701673  0.693414
UCEC       0.612778  0.671122  0.681924
LUSC       0.570422  0.609730  0.607094
BRCA       0.522846  0.597326  0.621638

In [10]:
pd.concat(grade_res,axis=1)[['RoationForest', 'XGB', 'LGB']]

      RoationForest       XGB       LGB
task
CESC       0.492634  0.607859  0.603956
KIRC       0.513963  0.608022  0.583777
LGG        0.671229  0.735792  0.736323
LIHC       0.550368  0.652950  0.699148
PAAD       0.490246  0.592898  0.628194
STAD       0.636267  0.767431  0.764846
UCEC       0.770515  0.881476  0.889864
HNSC       0.587229  0.733839  0.728773